tomcat_1:
  image: tomcat_admin
  expose:
    - "80"
    - "8080"
    - "41001"
    - "41002"
  command: catalina.sh run

tomcat_2:
  image: tomcat_admin
  expose:
    - "80"
    - "8080"
    - "41001"
    - "41002"
  command: catalina.sh run

haproxy:
  build: ../dockerfile-haproxy
 
  links:
   - tomcat_1
   - tomcat_2
  ports:
   - "8080:8080"
   - "80:80"
   - "70:70"

  expose:
   - "8080"
   - "80"
   - "70"

